package com.infalce.batch.domain.youtube.service;

import com.infalce.batch.domain.youtube.api.YoutubeApiClient.YoutubeChannelItem;
import com.infalce.batch.domain.youtube.api.YoutubeApiClient.YoutubeVideoItem;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class YoutubeBatchClassificationTest {

    @Test
    void identifiesAutoGeneratedTopicChannelsByTitleSuffix() {
        assertTrue(YoutubeChannelDiscoveryService.isTopicChannel(channel("Artist Name - Topic")));
        assertTrue(YoutubeChannelDiscoveryService.isTopicChannel(channel("Artist Name - TOPIC  ")));
    }

    @Test
    void doesNotIdentifyRegularChannelsAsTopicChannels() {
        assertFalse(YoutubeChannelDiscoveryService.isTopicChannel(channel("Artist Name")));
        assertFalse(YoutubeChannelDiscoveryService.isTopicChannel(channel("Topic")));
        assertFalse(YoutubeChannelDiscoveryService.isTopicChannel(channel(null)));
        assertFalse(YoutubeChannelDiscoveryService.isTopicChannel(null));
    }

    @Test
    void identifiesShortVideoWhenDurationIsShortEvenWithLandscapeThumbnail() {
        assertTrue(YoutubeVideoIngestionService.isShortVideo(video(1280, 720), 180));
    }

    @Test
    void identifiesShortVideoWhenThumbnailIsPortraitEvenWithLongDuration() {
        assertTrue(YoutubeVideoIngestionService.isShortVideo(video(720, 1280), 181));
    }

    @Test
    void doesNotIdentifyShortVideoWhenNeitherConditionMatches() {
        assertFalse(YoutubeVideoIngestionService.isShortVideo(video(1280, 720), 181));
        assertFalse(YoutubeVideoIngestionService.isShortVideo(video(null, null), null));
    }

    private YoutubeChannelItem channel(String title) {
        return new YoutubeChannelItem(
                "channel-id",
                title,
                null,
                null,
                null,
                null,
                null,
                0L,
                false,
                0L,
                0L,
                null
        );
    }

    private YoutubeVideoItem video(Integer thumbnailWidth, Integer thumbnailHeight) {
        return new YoutubeVideoItem(
                "video-id",
                "channel-id",
                null,
                null,
                null,
                List.of(),
                null,
                thumbnailWidth,
                thumbnailHeight,
                null,
                null,
                0L,
                0L,
                0L,
                false
        );
    }
}
