package com.infalce.batch.domain.youtube.service;

import com.infalce.batch.domain.youtube.api.YoutubeApiClient.YoutubeChannelItem;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class YoutubeCategoryChannelBatchServiceTest {

    @Test
    void identifiesAutoGeneratedTopicChannelsByTitleSuffix() {
        assertTrue(YoutubeCategoryChannelBatchService.isTopicChannel(channel("Artist Name - Topic")));
        assertTrue(YoutubeCategoryChannelBatchService.isTopicChannel(channel("Artist Name - TOPIC  ")));
    }

    @Test
    void doesNotIdentifyRegularChannelsAsTopicChannels() {
        assertFalse(YoutubeCategoryChannelBatchService.isTopicChannel(channel("Artist Name")));
        assertFalse(YoutubeCategoryChannelBatchService.isTopicChannel(channel("Topic")));
        assertFalse(YoutubeCategoryChannelBatchService.isTopicChannel(channel(null)));
        assertFalse(YoutubeCategoryChannelBatchService.isTopicChannel(null));
    }

    private YoutubeChannelItem channel(String title) {
        return new YoutubeChannelItem(
                "channel-id",
                title,
                null,
                null,
                null,
                null,
                null,
                0L,
                false,
                0L,
                0L,
                null
        );
    }
}
